### ISSUE TITLE
Output file having only RawScore,PredProb

### ISSUE THREAD

**Issue by nitinmahesh** [jpmml/jpmml-cascading#5]
Hi,
I tried to score one PMML model and in the output file i am getting RawScore,PredProb columns only.
I am not able to identify which records are having which RawScore,PredProb. 

I mean in the output files how can i get the other columns as well which will have the input columns as well(or least some kind of key/unique id) to identify which record this RawScore,PredProb relates to.

Output of the job:

hadoop@h nitin]$ head -5 ./OutHadoopCmd/part-00000
RawScore,PredProb
0.30726660686508417,0.648974194605812
0.1761462727982202,0.5871734046360437
0.25373184558861994,0.6242117165224929
0.2877732151464677,0.6400419974818216

Can you please suggest how can i get the unique keys from my input as well so that i can identify the Raw Score and Predicted Probability for the same.

**Comment by vruusmann** [comment]
It should be safe to assume that Cascading maintains the ordering of records between input and output CSV resources.

The PMML specification does not specify a mechanism for identifying individual records. This kind of service must be provided by the Apache Hadoop abstraction layer. You should search Cascading docs for things like "copying all input columns to output" or "adding identifiers to tuples" etc.

It would be possible to develop a quick workaround by declaring a special-purpose ID active field inside the PMML model, and copy its value from input to output (when executed with the JPMML-Evaluator library). However, I don't think this issue is a good place for discussing it. If you want to learn more, then you should post an appropriate question to the JPMML mailing list: https://groups.google.com/forum/#!forum/jpmml
